services:
  db:
    image: postgres:latest
    environment:
        POSTGRES_DB: customer.delivery
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
    ports:
        - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 2

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/customer.delivery
      - MAPS=YOUR_KEY_HERE
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"    
    environment:
      - REACT_APP_MAPS=YOUR_KEY_HERE
    command: npm start
